module.exports = {
  someSidebar: {
    Docusaurus: ['doc1', 'doc2', 'doc3'],
    Features: ['mdx'],

    Commands: [
      {
        type: 'category',
        label: 'c8y command',
        collapsed: true,
        items: [
          {
            type: 'autogenerated',
            dirName: 'api/c8y', // Generate sidebar slice from docs/api/c8y
          },
        ],
      },
    ],
  },
};
