source 'https://rubygems.org'

gem 'jekyll', '3.8.5'
gem "github-pages", '203', group: :jekyll_plugins

group :jekyll_plugins do
 # gem 'jekyll-feed', '0.13.0'
  #gem 'jekyll-seo-tag', '2.6.1'
  #gem 'jekyll-sitemap', '1.4.0'
  # gem 'github-pages', '203'

end