name: publish-linux-packages

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish_to_repo:
    runs-on: ubuntu-latest
    steps:
      # Skip publishing to jfrog as linux packages hosting has been moved
      # to a custom github repo: reubenmiller/go-c8y-cli-repo
      # Depending on how stable the new setup is, this task could be removed in the future
      # The publishing of the current released package is done via a different github action
      # "publish-linux-packages" once the release has been officially approved.
      - name: Publish Linux Packages
        if: ${{ false }}
        run: task publish-linux-packages
        env:
          JFROG_APIKEY: ${{ secrets.JFROG_APIKEY }}

      - name: Trigger publish to apt/apk/rpm repositories
        run: |
          gh workflow run publish.yml -R reubenmiller/go-c8y-cli-repo
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}

  publish-nuget:
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: install tooling
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        install-only: true

    - name: Install Task
      uses: arduino/setup-task@v1

    - name: Build Powershell Module
      run: task generate build

    - uses: actions/upload-artifact@v3
      with:
        name: ReleaseArtifacts
        path: |
          output_pwsh/PSc8y/

    - name: Publish Powershell Module (PSc8y)
      run: task publish-powershell
